# Generated by Django 5.2.7 on 2026-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('clinician', 'Clinician'), ('nurse', 'Nurse'), ('lab_tech', 'Lab Technician'), ('billing_staff', 'Billing Staff'), ('patient', 'Patient')], max_length=20),
        ),
    ]
